[sources.allow-org]
github = [
    "mintlayer", # allow any code from mintlayer's github
]

[licenses]
# we reject code without a license
confidence-threshold = 0.92
allow = [
    "Apache-2.0",
    "MIT",
    "Unicode-DFS-2016",
] # deny a license not in this set of licenses

[advisories]
db-path = "~/.cargo/advisory-dbs"
db-urls = [ "https://github.com/RustSec/advisory-db" ]
yanked = "warn"
ignore = []
